export { default as Home } from "./Home";
export { default as Links } from "./Links";
export { default as Contact } from "./Contact";
export { default as About } from "./About";
export { default as Login } from "./Login";
export { default as Player } from "./Player";
export { default as Register } from "./Register";
export { default as Search } from "./Search";
export { default as Reg } from "./Reg";
